- name: install and start nginx
  hosts: frontend
  become: true
  tasks:
  - name: install nginx
    ansible.builtin.package:
        name: nginx
        state: present

  - name: start nginx service
    ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes